# Metadata for the site header and footer
title: My website
description: A website made with GitHub Pages

# Set the production website URL when previewing
baseurl: "/write-the-docs"

# Markdown parser and theme settings
markdown: kramdown

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
